# Copyright 2016, EMC, Inc.

version: '2'

services:

  rackshift: # 8082
    image: rackshift:2.0
    network_mode: "host"
    privileged: true
    volumes:
      - "/opt/rackshift:/opt/rackshift"

  mysql:
    image: mysql:5.7.31
    network_mode: "host"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "/var/lib/mysql:/opt/rackshift/config/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
