name: upload release asset

on:
  create:
    tag:
      - "v1.4.0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Release File To Upload
        id: create_release_file
        env:
          RELEASE_VERSION: ${{github.ref}}
        run: |
          git clone https://github.com/rackshift/rackshift-installer.git
          cd rackshift-installer
          rm -rf docker .git
          cd ..
          chmod +x rackshift-installer/installer/install.sh
          version=`echo $RELEASE_VERSION | tr 'a-z' 'A-Z' | tr -d 'REFS/TAGS/'`
          filename=rackshift$version
          mv rackshift-installer $filename
          tar -czvf $filename.tar.gz $filename
          echo "::set-output name=VERSION::$(echo $version)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            # 快速开始
            仅需两步快速安装 RackShift：

             * 准备一台不小于 8 G内存且可以访问互联网的 64位 Linux 主机；
             * 以 root 用户执行如下命令一键安装 RackShift。
            ```sh
            sh -c "$(curl -sSL https://github.com/rackshift/rackshift/releases/latest/download/quick_start.sh)"
            ```

            ## 新增功能
            - 支持 浪潮/SuperMicro/DELL/h3c/曙光 远程 KVM
            - 开关机状态刷新
            - 自定义 post-installation 脚本
            - InspurM5 RAID
            - Suma，Lenovo 装机支持

            ## 功能优化
            - 密码打印脱敏
            - 兼容超微服务器产品型号缺失

            ## 问题修复
            - 插件选择裸金属分页问题
            - h3c 磁盘 raid 失败的问题
            - ubuntu 20.04 和 windows 2019 完成后状态显示错误的问题
            - 重新执行安装脚本覆盖之前配置的问题

            # 产品文档
            点击 [完整文档](https://rackshift.io) 查看完整的安装和使用文档
            # 离线安装包
            - 百度网盘下载链接: https://pan.baidu.com/s/1v0QYNZr1KGDlOxzlyoVGdA 提取码: ebz4

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./rackshift${{ steps.create_release_file.outputs.VERSION }}.tar.gz
          asset_name: rackshift${{ steps.create_release_file.outputs.VERSION }}.tar.gz
          asset_content_type: application/zip

      - name: Upload Quick Start Script
        id: upload-release-quick-start-shell
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./rackshift${{ steps.create_release_file.outputs.VERSION }}/installer/quick_start.sh
          asset_name: quick_start.sh
          asset_content_type: application/text
